name: Test package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v2
    - name: Install tox
      run: pip install tox
    - name: Run tox
      run: tox
